// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCjSgWfmawLeYsc57UYi6BTaV_kZU71YJA',
    appId: '1:125718176831:web:b5a9298be21af77561448a',
    messagingSenderId: '125718176831',
    projectId: 'dalel-app-ddefd',
    authDomain: 'dalel-app-ddefd.firebaseapp.com',
    storageBucket: 'dalel-app-ddefd.appspot.com',
    measurementId: 'G-CV8MH1RG61',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDe7z-YJxcvGGhBaTOVrTnUWHFcDvyD6AI',
    appId: '1:125718176831:android:e8e12628a97a17d061448a',
    messagingSenderId: '125718176831',
    projectId: 'dalel-app-ddefd',
    storageBucket: 'dalel-app-ddefd.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBV4g76e6waD__2MCXdPcdvZuSPxweV6ic',
    appId: '1:125718176831:ios:9ea24f17381db33261448a',
    messagingSenderId: '125718176831',
    projectId: 'dalel-app-ddefd',
    storageBucket: 'dalel-app-ddefd.appspot.com',
    iosBundleId: 'com.example.dalelEgypt',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBV4g76e6waD__2MCXdPcdvZuSPxweV6ic',
    appId: '1:125718176831:ios:9ea24f17381db33261448a',
    messagingSenderId: '125718176831',
    projectId: 'dalel-app-ddefd',
    storageBucket: 'dalel-app-ddefd.appspot.com',
    iosBundleId: 'com.example.dalelEgypt',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCjSgWfmawLeYsc57UYi6BTaV_kZU71YJA',
    appId: '1:125718176831:web:e3c9fd4de8a4b06e61448a',
    messagingSenderId: '125718176831',
    projectId: 'dalel-app-ddefd',
    authDomain: 'dalel-app-ddefd.firebaseapp.com',
    storageBucket: 'dalel-app-ddefd.appspot.com',
    measurementId: 'G-CM2F98D637',
  );
}
